services:
  user-container:
    container_name: continuous_driving_test
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    # Make sure the container can access the host's network
    privileged: true
    ipc: host
    network_mode: host
    # Start the container only when requested
    restart: 'no'
    # Enable support for GPU usage in the container.
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [ gpu ]
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: "/dds/cyclone_loopback.xml"
      ROS2CLI_DDS_WRAPPER_DISABLE: 1
    volumes:
      # Expose the DDS settings to the container
      - type: bind
        source: /data/app/avular/dds
        target: /dds
      # Mount a workspace to the container to allow the user to make persistent changes
      #- type: bind
      #  source: /data/user/containers/ws
      #  target: /home/user/ws
      # Expose the USB devices to the container
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
      - type: bind
        source: /dev/
        target: /dev/
    # Uncomment the following line to automatically start the ROS nodes
    # command: bash -c "source /home/user/ws/install/setup.bash && ros2 run navigation_tests continuous_driving_test"
    command: sleep infinity
    
    