x-common-variables: &common-variables
  ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
  DISPLAY: ${DISPLAY}
  ROS2CLI_DDS_WRAPPER_DISABLE: '1'
  SSH_AUTH_SOCK: "/run/user/ssh"
  RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
  CYCLONEDDS_URI: "/data/app/avular/dds/cyclone_loopback.xml"

x-common-config: &common-config
  network_mode: host
  tty: true
  init: true
  privileged: True
  ipc: host
  restart: 'always'

services:
  user-container:
    container_name: user
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    # Make sure the container can access the host's network
    environment:
      <<: *common-variables
    <<: *common-config
    # Start the container on boot, unless the container is stopped
    restart: unless-stopped
    # Enable support for GPU usage in the container.
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [ gpu ]
    volumes:
      # Mount a workspace to the container to allow the user to make persistent changes
      - type: bind
        source: /data/user/containers/ws
        target: /home/user/ws
      # Expose the USB devices to the container
      - type: bind
        source: /dev/bus/usb
        target: /dev/bus/usb
      - type: bind
        source: /dev/
        target: /dev/
      - type: bind
        source: /data/app/avular/dds
        target: /data/app/avular/dds
      - type: bind
        source: /tmp
        target: /tmp
    # Uncomment the following line to automatically start the ROS nodes
    #command: ros2 launch pkg launch_file.py
    # command: sleep infinity
    command: ros2 run v4l2_camera v4l2_camera_node --ros-args -p video_device:=/dev/video-front -p pixel_format:=GREY -p output_encoding:=mono8 -p image_size:=[1600,1300] -p brightness:=5 -p exposure_absolute:=10
