name: main

on:
  push:
    branches:
      - main
      - origin
      - vertex
  pull_request:
    branches:
      - main
      - origin
      - vertex

concurrency:
  group: main-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get the version
      id: version
      run: echo "version=$(git describe --tags --always)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.ref_name == 'vertex' }}
        tags: |
            ghcr.io/avular-robotics/user-container:vertex-unstable
        platforms: linux/arm64
        cache-from: type=gha
        cache-to: type=gha,mode=max
